var languages = [
    {
        id: "UA", 
        name : "УКР",
        locatedIn: " в ",
        born: {"M": "Народився", "F": "Народилася"},
        died: {"M": "Помер", "F": "Померла"},
        parents: "Батьки",
        and: " і ",
        buried: {"M": "Похований", "F": "Похована"},
        occupation: "Праця",
        married: {"M": "Одружився з ", "F": "Вийшла за заміж з "},
        divorced: "Розлучились ",
        yearsOld: "років",
        // Relationship calculator
        samePerson: "Та сама людина",
        siblings: {"MM": "брати", "MF": "брат/сестра", 
        "FM": "сестра/брат", "FF": "сестри"},
        cousins: {"MM": "кузини", "MF": "кузини", "FM": "кузини",
        "FF": "кузинки"},
        child: {"M": "син", "F": "дочка"},
        parent: {"M": "батько", "F": "мама"},
        grandparent: {"M": "дідо", "F": "баба"},
        grandchild: {"M": "внук", "F": "внучка"},
        great: "пра",
        auntUncle: {"MM": "стрийко", "MF": "вуйко", "FM": "стриянка", "FF": "тета"},
        nieceNephew: {"M": "племінник", "F": "племінниця"},
        removed: "віддалені",
    },
    {
        id: "EN", 
        name: "ENG",
        locatedIn: " in ",
        born: {"M": "Born", "F": "Born"},
        died: {"M": "Died", "F": "Died"},
        parents: "Parents",
        and: " and ",
        buried: {"M": "Buried", "F": "Buried"},
        occupation: "Occupation",
        married: {"M": "Married ", "F": "Married "},
        divorced: "Divorced ",
        yearsOld: "years old",
        // Relationship calculator
        samePerson: "Same person",
        siblings: {"MM": "Brothers", "MF": "Brother/Sister", 
        "FM": "Sister/Brother", "FF": "Sisters"},
        cousins: {"MM": "cousins", "MF": "cousins", "FM": "cousins",
        "FF": "кузинки"},
        child: {"M": "son", "F": "daughter"},
        parent: {"M": "father", "F": "mother"},
        grandparent: {"M": "grandfather", "F": "grandmother"},
        grandchild: {"M": "grandson", "F": "granddaughter"},
        great: "great",
        auntUncle: {"MM": "uncle", "MF": "uncle", "FM": "aunt", "FF": "aunt"},
        nieceNephew: {"M": "nephew", "F": "niece"},
        removed: "removed",
    },
];